server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.campus.api.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    use-generated-keys: true
    default-statement-timeout: 60
    cache-enabled: false

jwt:
  secret: ${JWT_SECRET:4Dj8KzEwNcMqL5pRtVx3yA9BgFhJnQsW2uX7vZYaCbPmTkHd6e}
  expiration: 604800000
  header: Authorization
  token-prefix: "Bearer "

wx:
  miniapp:
    appid: ${WX_APPID:wx5606485cb380b618}
    secret: ${WX_SECRET:388fe8cb4a82797712b3c41b6463daee}

upload:
  path: /tmp/upload
  allowed-types: image/jpeg,image/png,image/gif
  max-size: 5242880
  domain: ${DOMAIN_URL} 